const $=id=>document.getElementById(id);async function api(p,o={}){const r=await fetch(p,o),j=await r.json();if(!r.ok)throw Error(j.error||'Erro');return j}
function render(s){$('channel').textContent=s.channel||'Nenhuma';$('status').textContent=s.status==='playing'?'🟢 A ver live':'⏹️ Visualização parada';$('online').textContent='● Online';$('online').className='pill ok';const f=$('favorites');f.innerHTML='';(s.favorites||[]).forEach(c=>{const d=document.createElement('div');d.className='fav';const b=document.createElement('button');b.textContent=c;b.onclick=()=>selectChannel(c);const x=document.createElement('button');x.textContent='×';x.className='x';x.onclick=()=>favorite(c,'remove');d.append(b,x);f.append(d)})}
function dropCard(c){const box=document.createElement('div');box.className='dropCampaign';const h=document.createElement('div');h.className='dropHead';h.innerHTML=`<strong>${esc(c.game||'Jogo')}</strong><span>${esc(c.name||'Campanha')}</span>`;box.append(h);(c.drops||[]).forEach(d=>{const row=document.createElement('div');row.className='dropRow';const p=Math.max(0,Math.min(100,Number(d.percent)||0));row.innerHTML=`<div class="dropName">${esc(d.name)} ${d.claimed?'✓':''}</div><div class="bar"><i style="width:${p}%"></i></div><div class="dropMeta">${d.current} / ${d.required} min · ${p}%</div>${d.rewards?.length?`<div class="reward">🎁 ${d.rewards.map(esc).join(', ')}</div>`:''}`;box.append(row)});return box}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function renderDrops(){const box=$('drops'),msg=$('dropsStatus');box.innerHTML='';msg.textContent='A consultar Drops…';try{const d=await api('/api/drops');if(!d.ok){msg.textContent='⚠️ '+d.error;return}if(!d.campaigns?.length){msg.textContent='Nenhuma campanha em progresso para os jogos selecionados.';return}msg.textContent=`${d.campaigns.length} campanha(s) encontrada(s).`;d.campaigns.forEach(c=>box.append(dropCard(c)))}catch(e){msg.textContent='⚠️ '+e.message}}
async function refresh(){try{render(await api('/api/status'))}catch(e){$('online').textContent='● Offline';$('online').className='pill';$('status').textContent='Sem ligação à Raspberry'}}
async function selectChannel(c){try{render(await api('/api/channel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:c})}));$('controlMessage').textContent='Canal selecionado.'}catch(e){$('controlMessage').textContent=e.message)}}
async function start(){try{render(await api('/api/start'));$('controlMessage').textContent='Live iniciada.'}catch(e){$('controlMessage').textContent=e.message)}}async function stop(){try{render(await api('/api/stop'));$('controlMessage').textContent='Visualização terminada.'}catch(e){$('controlMessage').textContent=e.message)}}async function favorite(c,a){try{render(await api('/api/favorite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:c,action:a})}))}catch(e){$('controlMessage').textContent=e.message)}}
$('openBtn').onclick=()=>{const c=$('channelInput').value.trim();if(c)selectChannel(c)};$('channelInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('openBtn').click()});$('startBtn').onclick=start;$('stopBtn').onclick=stop;$('reloadBtn').onclick=start;$('refreshBtn').onclick=refresh;$('dropsRefresh').onclick=renderDrops;$('loginBtn').onclick=async()=>{try{$('loginMsg').textContent=(await api('/api/login')).message}catch(e){$('loginMsg').textContent=e.message}};$('addGameBtn').onclick=async()=>{const name=$('gameInput').value.trim();if(!name)return;try{await api('/api/drops/games',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});$('gameInput').value='';renderDrops()}catch(e){$('dropsStatus').textContent=e.message}};refresh();renderDrops();setInterval(refresh,10000);setInterval(renderDrops,60000);
